apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: example-voting-app-rohit
    name: db
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
              name: postgres
    metadata:
      name: db
      labels:
        app: example-voting-app-rohit
        name: db
  selector:
    matchLabels:
      app: example-voting-app-rohit
      name: db
