apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: example-voting-app-rohit
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-service
  selector:
    app: example-voting-app-rohit
    name: redis