apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    - app: example-voting-app-rohit
      name: result-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
              name: result-app
    metadata:
      name: resut-app
      labels:
        - app: example-voting-app-rohit
          name: result-app
  selector:
    matchLabels:
      app: example-voting-app-rohit
      name: result-app