apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: example-voting-app-rohit
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: result-service
  selector:
    app: example-voting-app-rohit
    name: result-app