apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  labels:
    - app: example-voting-app-rohit
      name: voting-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
              name: voting-app
    metadata:
      name: voting-app
      labels:
        - app: example-voting-app-rohit
          name: voting-app
  selector:
    matchLabels:
      app: example-voting-app-rohit
      name: voting-app
