apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: example-voting-app-rohit
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: voting-service
  selector:
    app: example-voting-app-rohit
    name: voting-app